
const all_fonts = [
    "Scheherazade-Regular.ttf",
    "Scheherazade-Bold.ttf",
    "Bahij ASVCodar-Regular.ttf",
    "Bahij ASVCodar-Bold.ttf",
    "Bahij Aban-Bold.ttf",
    "Bahij Badiya-Bold.ttf",
    "Bahij Badiya-Regular.ttf",
    "Bahij Badr-Bold.ttf",
    "Bahij Badr-Light.ttf",
    "Bahij Baraem-Regular.ttf",
    "Bahij Droid Naskh-Bold.ttf",
    "Bahij Droid Naskh-Regular.ttf",
    "Bahij Fedra Arabic-Bold.ttf",
    "Bahij Fedra Arabic-Regular.ttf",
    "Bahij Firas-Regular.ttf",
    "Bahij Greta Arabic-Bold.ttf",
    "Bahij Greta Arabic-Medium.ttf",
    "Bahij Greta Arabic-Regular.ttf",
    "Bahij Hassan-Bold.ttf",
    "Bahij Hassan-Regular.ttf",
    "Bahij Helvetica Neue-Bold.ttf",
    "Bahij Helvetica Neue-Light.ttf",
    "Bahij Helvetica Neue-Roman.ttf",
    "Bahij Homa-Bold.ttf",
    "Bahij Insan-Bold.ttf",
    "Bahij Insan-Regular.ttf",
    "Bahij Insan-Thin.ttf",
    "Bahij Jalal-Bold.ttf",
    "Bahij Jalal-Regular.ttf",
    "Bahij Janna-Bold.ttf",
    "Bahij Janna-Regular.ttf",
    "Bahij Karim-Regular.ttf",
    "Bahij Koodak-Bold.ttf",
    "Bahij Koodak-Regular.ttf",
    "Bahij Koufiya-Bold.ttf",
    "Bahij Koufiya-Regular.ttf",
    "Bahij Lotus-Bold.ttf",
    "Bahij Lotus-Light.ttf",
    "Bahij Maged-Bold.ttf",
    "Bahij Maged-Regular.ttf",
    "Bahij Midan-Black.ttf",
    "Bahij Midan-Regular.ttf",
    "Bahij Mitra-Bold.ttf",
    "Bahij Mitra-Regular.ttf",
    "Bahij Muna-Black.ttf",
    "Bahij Muna-Bold.ttf",
    "Bahij Muna-Regular.ttf",
    "Bahij Myriad Arabic-Bold.ttf",
    "Bahij Myriad Arabic-Regular.ttf",
    "Bahij Nassim-Bold.ttf",
    "Bahij Nassim-Regular.ttf",
    "Bahij Nazanin-Bold.ttf",
    "Bahij Nazanin-Regular.ttf",
    "Bahij Palatino Arabic-Regular.ttf",
    "Bahij Palatino Sans Arabic-Bold.ttf",
    "Bahij Palatino Sans Arabic-Regular.ttf",
    "Bahij Roya-Bold.ttf",
    "Bahij Roya-Regular.ttf",
    "Bahij SultanNahia-Regular.ttf",
    "Bahij Tanseek Pro-Bold.ttf",
    "Bahij Tanseek Pro-Regular.ttf",
    "Bahij TheSansArabic-Black.ttf",
    "Bahij TheSansArabic-Bold.ttf",
    "Bahij TheSansArabic-ExtraBold.ttf",
    "Bahij TheSansArabic-ExtraLight.ttf",
    "Bahij TheSansArabic-Light.ttf",
    "Bahij TheSansArabic-Plain.ttf",
    "Bahij TheSansArabic-SemiBold.ttf",
    "Bahij TheSansArabic-SemiLight.ttf",
    "Bahij Titr-Bold.ttf",
    "Bahij Traffic-Bold.ttf",
    "Bahij Traffic-Regular.ttf",
    "Bahij Uthman Taha-Bold.ttf",
    "Bahij Uthman Taha-Regular.ttf",
    "Bahij Yakout-Bold.ttf",
    "Bahij Yakout-Regular.ttf",
    "Bahij Yekan-Bold.ttf",
    "Bahij Yekan-Regular.ttf",
    "Bahij Zar-Bold.ttf",
    "Bahij Zar-Regular.ttf",
    "LateefGR-Regular.ttf",
    "AwamiNastaliq-Regular.ttf"]